// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "MoneyForest": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/odiak/MoneyForest/design
// --out=$(GOPATH)/src/github.com/odiak/MoneyForest
// --version=v1.3.0

package app

import (
	"fmt"
	"strings"
)

// AccountHref returns the resource href.
func AccountHref(accountID interface{}) string {
	paramaccountID := strings.TrimLeftFunc(fmt.Sprintf("%v", accountID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/accounts/%v", paramaccountID)
}

// TransactionHref returns the resource href.
func TransactionHref(transactionID interface{}) string {
	paramtransactionID := strings.TrimLeftFunc(fmt.Sprintf("%v", transactionID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/transactions/%v", paramtransactionID)
}
