// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "MoneyForest": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/odiak/MoneyForest/design
// --out=$(GOPATH)/src/github.com/odiak/MoneyForest
// --version=v1.3.0

package app
